version: '3'

services:
# Install Jenkins with Docker on the same image
  jenkins:
    image: marroyo777/jocker:0.1
    container_name: jenkins
    privileged: true
    user: root
    ports: 
      - 8800:8080
      - 50000:5000
    volumes:
      - jenkins_compose:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local
  sonarqube:
    image: sonarqube:8.9-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=admin
      - sonar.jdbc.password=admin
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - logs:/opt/sonarqube/logs
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
    networks:
      - local

  db:
    image: postgres:13.1
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - pg_db:/var/lib/postgresql
      - pg_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - local
  
volumes:
  jenkins_compose:
  pg_db:
  pg_data:
  logs:
  data:
  extensions:
networks:
  local:
